import MobileMenu from '@/components/mobile-menu';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const events = await getEvents();
  // const liveEvent = events.find((event) =>
  //   isEventLive(event.start, event.end),
  // )?.$id;

  return (
    <html lang="en">
      <body
        className={cn('leading-relaxed antialiased', inter.className)}
        suppressHydrationWarning={true}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
